### ISSUE TITLE
ks init fails when using $KUBECONFIG env var

### ISSUE THREAD

**Issue by lblackstone** [ksonnet/ksonnet#251]
I'm getting the following error when trying to run `ks init ks-example`:

`ERROR No current context found. Make sure a kubeconfig file is present`

My cluster's kubeconfig is referenced in the `KUBECONFIG` env var, and I can interact with the cluster via `kubectl`.

This appears to be a regression introduced in d252456c2cf1d1bace58b96162ad6180b8a0bd9b

Here is the kubeconfig I'm using:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>:443
  name: levi
contexts:
- context:
    cluster: levi
    user: kubelet
  name: ""
current-context: ""
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate-data: <redacted
    client-key-data: <redacted
```
