### ISSUE TITLE
prototypes can't rely on a registry name, but they do

### ISSUE THREAD

**Issue by redbaron** [ksonnet/ksonnet#262]
Users are free to import registries under whatever name they want. 

```
kind: ksonnet.io/app
libraries:
  redis:
    registry: not-incubator
registries:
  not-incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
```

which would pull registry into `vendor/not-incubator`. 

Prototype in that registry use imports like following:

```
local redis = import 'incubator/redis/redis.libsonnet'; 
```

so that `incubator/` path is hardcoded to "cannonical" registry name, which is fragile and wont work if use choose to spcify registry under different name
