### ISSUE TITLE
pkg -> prototype -> component hierarchy is unnecessary complicated

### ISSUE THREAD

**Issue by redbaron** [ksonnet/ksonnet#263]
Current way of pulling packages, then specifying components by using prototypes from a package is confusing and I can't see what it buys comparing to a more direct approach where `app.yaml` specifies components directly.

Something along the lines would achieve same result in a single step AND would allow packages to be updated per component, which is not possible right now:

```
apiVersion: 0.0.1
kind: ksonnet.io/app
components:
  redis-app:
    gitVersion:  ....
    name: redis
    prototype: redis-stateless
    registry: incubator
registries:
  incubator:
    ...
    uri: github.com/ksonnet/parts/tree/master/incubator
```

this would create following structure:
```
components/
  redis-app.jsonnet
  redis-app/
    redis-stateless.jsonnet
    redis.libsonnet (and rest of the files from incubator/redis/)
```

where `redis-app.jsonnet` is:
```
import './redis-app/redis-stateless.jsonnet'
```

and `redis-app/redis-stateless.jsonnet` is rendered `redis-stateless` prototype as it is being rendered now (I believe comments are removed and `local params = ...` added).

This also solves https://github.com/ksonnet/ksonnet/issues/262 , because prototypes can now reference packages they are part of using relative paths:

```
local redis = import './redis.libsonnet'; 
```
