### ISSUE TITLE
FYI gotchas with ksonnet and K8s in Docker on Mac

### ISSUE THREAD

**Issue by jlewi** [ksonnet/ksonnet#320]
Some Kubeflow users have reported needing to do some extra work to make ksonnet work with Kubernetes running in Docker on mac.

The solution is described here.
https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#docker-for-mac

**Comment by bryanl** [comment]
The current plan is to tackle this in a patch release to 0.9

**Comment by bryanl** [comment]
I took at a look at Docker for Mac today, and it creates the correct item in ~/.kube/config:

```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop-cluster
```

This should no longer be a gotcha.
