### ISSUE TITLE
ks import doesn't take namespace into account

### ISSUE THREAD

**Issue by ankushagarwal** [ksonnet/ksonnet#467]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Tried `ks import` with this yaml file, but it fails because both of the objects in this yaml have the same kind and name.
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: a
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: b
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
```

**What you expected to happen**:
Create two ksonnet components successfully

**How to reproduce it (as minimally and precisely as possible)**:
ks import -f above-yaml-file.yaml

**Environment**:
- ksonnet version (use `ks version`):
master
- Kubernetes version (use `kubectl version`):
1.10

Maybe a hash-prefix could be used in selecting the file name/component name. For example the above yaml would generate

pod-nginx-j97w.yaml
pod-nginx-2vz0.yaml
