### ISSUE TITLE
Stronger YAML support in ksonnet

### ISSUE THREAD

**Issue by ankushagarwal** [ksonnet/ksonnet#470]
/kind feature / proposal 

jsonnet and libsonnet is a huge barrier for ksonnet adoption for developers who work on k8s - yaml is their bread and butter. I am really excited to see [drop in yaml support for ksonnet](https://github.com/ksonnet/ksonnet/issues/240)!

It will be great to have stronger support for yaml components in ksonnet. Let's take an example of a workflow which a k8s app developer uses. I want to deploy a mysql database for my wordpress application. I start by using an example from the kubernetes examples repo : [mysql-deployment.yaml](https://raw.githubusercontent.com/kubernetes/website/master/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/mysql-deployment.yaml)

Here is what my ideal experience with ksonnet would look like:

1. I already have a ksonnet app and I want to use ksonnet to manage environments and parameters, so I just download this to `my-ks-app/components/mysql-deployment.yaml`. 
2. I want to use different images for staging environment and production environment. So I parametrize the `image` field in `Deployment`. 
3. I also want to avoid repetetion in the component, so I parametrize the `metadata.labels` field for all three objects. 
4. So my final yaml would look something like this

```
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels: {{ .Labels }}
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels: {{ .Labels }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels: {{ .Labels }}
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: {{ .Image }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
```

5. Once I have done this, I use `ks` to set the params for this component for staging and prod

```
ks param set mysql-deployment Labels '{"app": "mysql"}'
ks param set mysql-deployment Image 'mysql-image:5.7' --env=prod
ks param set mysql-deployment Image 'mysql-image:dirty' --env=staging
```

6. and then deploy to my staging env

```
ks apply staging -c mysql-devel
```

Here is how my workflow looks like in the current version of ksonnet

1. An existing ksonnet prototype does not exist for a mysql deployment with PV, so I cannot use `ks generate ...`
2. ks now supports importing yaml components, so now I can use `ks import -f https://raw.githubusercontent.com/kubernetes/website/master/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/mysql-deployment.yaml`. This creates 3 components in my ks app, I just wanted one.
3. I parametrize Labels using `ks param set`, but I would have to do this for all the three components separately.

```
ks param set service-wordpress-mysql metadata.labels '{"app": "mysql"}'
ks param set persistentvolumeclaim-mysql-pv-claim metadata.labels '{"app": "mysql"}'
ks param set deployment-wordpress-mysql metadata.labels '{"app": "mysql"}'
```

4. I also cannot parametrize Image since it is part of the containers array.
5. I would have to convert my app manifest to a jsonnet / libsonnet file - Here is where a lot of people have difficulty.

While jsonnet has a lot of advantages in being able to write very sophisticated configs, it is not a very human friendly lanuage. For example: [here](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/iap.libsonnet) is a hand-written jsonnet file in kubeflow. It is very challenging to read and make sense of this.

The point that I'm trying to drive is that having stronger support for yaml components will make life much easier for adoption of ksonnet for k8s developers.

/cc @bryanl @jessesuen since this has been discussed partially in https://github.com/ksonnet/ksonnet/issues/426
