### ISSUE TITLE
Omit printing gitVersion in app.yaml if it is missing

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#511]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

```yaml
libraries:
  core:
    gitVersion: null
    name: core
    registry: kubeflow
```

**What you expected to happen**:

```yaml
libraries:
  core:
    name: core
    registry: kubeflow
```

**Environment**:
- ksonnet version (use `ks version`): 0.10.1
