### ISSUE TITLE
Revise diff to only work with managed objects / fields

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#529]
ksonnet has the ability to show differences in configurations and objects which exist in the cluster. The following operations are defined:

diff location:env
diff location1:env location2:env

Where _location_ is either `remote` or `local` and _env_ is the environment name.

Tasks
- [x] Tag owned fields annotation
- [x] Tag owned object label
- [x] Create JSON object using managed fields
- [ ] Re-work existing diff process to use generated JSON object to do diffs

To ensure the diff process only works with objects and fields managed by ksonnet, ksonnet will add an annotation to objects (`ksonnet.io/managed`) containing the fields which have been updated.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    ksonnet.io/managed: '{managed data}'
```

The `ksonnet.io/managed` annotation is an object which contains a gzip'd, base64 encoded version of the file generated by ksonnet.
