### ISSUE TITLE
Support environment -> versioned package mapping

### ISSUE THREAD

**Issue by shomron** [ksonnet/ksonnet#631]
/kind feature

Environments should support versioned references to installed packages.
This can be represented by adding `LibraryConfigs` to `EnvironmentConfig`, e.g.

```
environments:
  default:
    destination:
      namespace: default
      server: https://192.168.64.3:8443
    k8sVersion: v1.10.0
    path: default
    libraries:
      nginx:
        name: nginx
        registry: incubator
        version: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      spinnaker:
        name: spinnaker
        registry: helm-stable
        version: 2.3.4
```

The global `LibraryConfigs` will still be supported at a lower precedence.
