### ISSUE TITLE
Modules unusable - environment param overrides for module are not used with apply/show

### ISSUE THREAD

**Issue by rosskevin** [ksonnet/ksonnet#826]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When using modules, param overrides does not work

**What you expected to happen**:
Param overrides for modules should work just like when not using modules

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup
```
ks init guestbook
cd guestbook
ks module create foo
ks env targets default --module foo
ks generate deployed-service bar --module foo --image gcr.io/heptio-images/ks-guestbook-demo:0.1 --type ClusterIP
# show default params
ks param list --module foo --env default
```

2. override containerPort
`vi environments/default/params.libsonnet`
content should be:

```
local params = std.extVar("__ksonnet/params");
local globals = import "globals.libsonnet";
local envParams = params + {
  components +: {
    bar +: {
      containerPort: 9999
    },
  },
};

{
  components: {
    [x]: envParams.components[x] + globals, for x in std.objectFields(envParams.components)
  },
}
```
3. Verify param overrides (works!):

```
~/p/g/t/guestbook ❯❯❯ ks param list --module foo --env default
COMPONENT PARAM         VALUE
========= =====         =====
bar       containerPort 9999
bar       image         'gcr.io/heptio-images/ks-guestbook-demo:0.1'
bar       name          'bar'
bar       replicas      1
bar       servicePort   80
bar       type          'ClusterIP'
```

4. Show **DOES NOT USE OVERRIDE** `containerPort: 9999`:

```
ks show default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: foo.bar
  name: bar
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: bar
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: foo.bar
  name: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: bar
        ports:
        - containerPort: 80
```

**Anything else we need to know?**:

**Environment**:
ksonnet version: 0.12.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
